name: Deploy Web UI

on:
  push:
    branches: ['master']

jobs:
  pre-build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add yarn
        run: |
          npm i -g yarn

      - name: Install dependencies
        run: |
          yarn install

  build:
    runs-on: self-hosted
    needs: pre-build

    steps:
      - name: Determinate build version
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Export variables and build
        run: |
          export NEXT_PUBLIC_PRERELEASE_MODE="${{ vars.GH_PRERELEASE_MODE }}"
          export NEXT_PUBLIC_BUILD_VERSION="${{ steps.vars.outputs.sha_short }}_${{ github.run_number }}"
          yarn run build:std
          unset NEXT_PUBLIC_PRERELEASE_MODE
          unset NEXT_PUBLIC_BUILD_VERSION

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Move to www directory
        run: |
          rm -rf /var/www/jwizard/*
          cp -r build/* /var/www/jwizard/

      - name: Restart process
        run: |
          pm2 restart ecosystem.config.js --only ${{ vars.PM2_WEB_UI_NAME }} --silent
          pm2 save
