name: Deploy Web UI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - uses: jongwooo/next-cache@v1

      # - name: Add yarn
      #   run: |
      #     npm i -g yarn

      # - name: Install dependencies
      #   run: |
      #     yarn install --frozen-lockfile

      # - name: Determinate build version
      #   id: vars
      #   run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # - name: Export variables and build
      #   run: |
      #     export NEXT_PUBLIC_PRERELEASE_MODE="${{ vars.GH_PRERELEASE_MODE }}"
      #     export NEXT_PUBLIC_BUILD_VERSION="${{ steps.vars.outputs.sha_short }}_${{ github.run_number }}"
      #     yarn run build:std
      #     unset NEXT_PUBLIC_PRERELEASE_MODE
      #     unset NEXT_PUBLIC_BUILD_VERSION

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Stop existing process
        run: |
          pm2 stop /root/ecosystem.config.js --only ${{ vars.PM2_WEB_UI_NAME }} --silent
          pm2 save

      - name: Remove previous compilation files
        run: |
          rm -rf /var/www/jwizard/*
          rm -rf /var/www/jwizard/{*,.[!.]*,..?*} 2> /dev/null

      - name: Move to /var/www directory
        run: |
          sudo cp -rT public /var/www/jwizard

      - name: Init process
        run: |
          pm2 start /root/ecosystem.config.js --only ${{ vars.PM2_WEB_UI_NAME }} --silent
          pm2 save
