name: Deploy to VPS

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Determinate build version
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Add yarn
        run: |
          npm i -g yarn

      - name: Install
        run: |
          yarn install

      - name: Export variables and build
        run: |
          export VITE_API_URL="${{ secrets.GH_API_URL }}"
          export VITE_SIGNAL_API_URL="${{ secrets.GH_SIGNAL_API_URL }}"
          export VITE_ORG_LINK="${{ vars.GH_ORG_LINK }}"
          export VITE_PRERELEASE_MODE="${{ vars.GH_PRERELEASE_MODE }}"
          export VITE_BUILD_VERSION="${{ steps.vars.outputs.sha_short }}_${{ github.run_number }}"
          yarn run build

      - name: Deploy
        run: cp -r dist/* /var/www/jwizard/
