name: Update packages cache

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-packages.yml'
      - 'yarn.lock'

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tools repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/jwizard-tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Grand permissions
        run: chmod +x exec/run-with-config

      - name: Run packages grabber
        run: exec/run-with-config packages_grabber \
          "${{ secrets.CONFIG_FILE_CONTENT }}" \
          --repo ${{ github.repository }}
