FROM node:20-alpine

ENV BUILD_DIR=/docker/landing-page
ENV ENTRY_DIR=/app/jww-lp

# next.js stuff
# hostname must be set to any address, localhost or 127.0.0.1 not working
ENV HOSTNAME=0.0.0.0
ENV PORT=8080
ENV NEXT_SHARP_PATH=node_modules/sharp

RUN addgroup -S jwgroup && \
    adduser -S jwuser -G jwgroup

WORKDIR $ENTRY_DIR

RUN chown jwuser:jwgroup $ENTRY_DIR
COPY --chown=jwuser:jwgroup $BUILD_DIR/build/ $ENTRY_DIR

LABEL maintainer="JWizard <info@jwizard.pl>"

EXPOSE $PORT

USER jwuser

ENTRYPOINT [ "node", "server.js" ]
